# Generated by Django 6.0.3 on 2026-05-14 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_genre_name_alter_language_name_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='movies.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_order_id',
            field=models.CharField(default='temp_order_id', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
