# Generated by Django 6.0.3 on 2026-05-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
