# Generated by Django 6.0.3 on 2026-05-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('movies', '0006_alter_genre_name_alter_language_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='show',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='theatre',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='show',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='show',
            name='movie',
        ),
        migrations.CreateModel(
            name='SeatLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('expired', 'Expired')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.theater')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BookedSeat',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Theatre',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Screen',
        ),
        migrations.DeleteModel(
            name='Show',
        ),
        migrations.AddIndex(
            model_name='seatlock',
            index=models.Index(fields=['show'], name='bookings_se_show_id_993672_idx'),
        ),
        migrations.AddIndex(
            model_name='seatlock',
            index=models.Index(fields=['expires_at'], name='bookings_se_expires_c4b1da_idx'),
        ),
        migrations.AddConstraint(
            model_name='seatlock',
            constraint=models.UniqueConstraint(fields=('show', 'seat'), name='unique_show_seat_lock'),
        ),
    ]
