# Generated by Django 6.0.3 on 2026-05-09 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_seatlock_unique_show_seat_lock_and_more'),
        ('movies', '0006_alter_genre_name_alter_language_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seatlock',
            name='unique_show_seat_lock',
        ),
        migrations.AddConstraint(
            model_name='seatlock',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('show', 'seat'), name='unique_active_seat_lock'),
        ),
    ]
