# Generated by Django 6.0.3 on 2026-04-25 06:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genre_language_movie_genres_movie_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
