# Generated by Django 6.0.3 on 2026-05-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
