# Generated by Django 6.0.3 on 2026-07-21 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0011_remove_seat_is_booked_alter_seat_theater'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieNight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue_type', models.CharField(choices=[('Cinema', 'Cinema'), ('Home', 'Home')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional message for your friends.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_movie_nights', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_nights', to='movies.movie')),
                ('theater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_nights', to='movies.theater')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_night_invitations', to=settings.AUTH_USER_MODEL)),
                ('movie_night', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='planner.movienight')),
            ],
            options={
                'ordering': ['-invited_at'],
                'unique_together': {('movie_night', 'invited_user')},
            },
        ),
    ]
