# Generated by Django 6.0.3 on 2026-07-21 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movienight',
            name='invited_users',
            field=models.ManyToManyField(blank=True, help_text='Users invited to this movie night.', related_name='invited_movie_nights', to=settings.AUTH_USER_MODEL),
        ),
    ]
